version: '3.8'

services:
  app:
    build: .
    container_name: miror_parser
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./routes.yml:/app/routes.yml
      - ./sessions:/app/src/sessions
      - ./data:/app/data
      - ./logs:/app/src/logs
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=/app/data/messages.db
